defaults:
  - dataset
  - augmentation

# ckpt_name: '16+2'
ckpt_name: '0+4'
ckpt_path: False

augmentation:
  audio_effects:
    pink_noise:
      noise_std: 0.0001
    mp3_compression:
      sample_rate: ${sample_rate}
      bitrate: 64k # should be a string e.g. "8k", "32k".. cf ffmpeg to see available bitrates
    aac_compression:
      sample_rate: ${sample_rate}
      bitrate: 64k
    opus_compression:
      sample_rate: ${sample_rate}
      bitrate: 64k

aug_weights:
  speed: 0
  updownresample: 0
  echo: 0 # nan
  quantize_audio: 0
  pink_noise: 0 #1
  lowpass_filter: 0
  highpass_filter: 0
  bandpass_filter: 0
  smooth: 0
  boost_audio: 0
  duck_audio: 0
  mp3_compression: 0 #1 # eval only never use in training even if eval_acc low
  aac_compression: 0 # eval only never use in training even if eval_acc low
  opus_compression: 0 # eval only never use in training even if eval_acc low
  encodec: 0
  identity: 0 # no augmentation